#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux
# https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding
if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
