[character]
success_symbol = "\\$"
error_symbol = "[\\$](red)"

[python]
disabled = false
pyenv_version_name = false
format = '[(\($virtualenv\) )]($style)'

[ruby]
disabled = true

[nodejs]
disabled = true

[aws]
disabled = true

[php]
disabled = true

[gcloud]
disabled = true
